version: "3.8"
services:

  init:
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/run/src
    environment:
      - PYTHONPATH=/run
    networks:
      - shared_network
    command: "python3 src/init_database.py"

  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/run/src
    environment:
      - PYTHONPATH=/run
    command: "fastapi run src/server.py --host 0.0.0.0 --port 8000"
#    command: "uvicorn src.server:app --host 0.0.0.0 --port 8000 --loop asyncio --workers 16"
    networks:
      - shared_network

  mysql:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
      MYSQL_DATABASE: template_db
    volumes:
      - ./volume/mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge